sudo: required
services:
  - docker

before_install:
  - docker build -t kpadania/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -d kpadania/react-test npm run test

after_success:
  - docker build -t kpadania/multi-client ./client
  - docker build -t kpadania/multi-nginx ./nginx
  - docker build -t kpadania/multi-server ./server
  - docker build -t kpadania/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kpadania/multi-client
  - docker push kpadania/multi-nginx
  - docker push kpadania/multi-server
  - docker push kpadania/multi-worker 

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-830990676668"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"